import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

// গ্লোবাল ব্র্যান্ডিং কনফিগারেশন
const BRANDING = {
    name: "VAULT PRO",
    credit: "Design and Development by Rahul",
    url: "https://cash-book-pro.vercel.app/",
    signature: "SOURCE: CASHBOOK PRO DIGITAL LEDGER"
};

// ১. এক্সেল জেনারেশন ইঞ্জিন
export const generateExcelProtocol = (data: any[], bookName: string) => {
    const worksheetData = [
        [BRANDING.signature],
        ["VAULT IDENTITY: " + bookName.toUpperCase()],
        ["GENERATED ON: " + new Date().toLocaleString()],
        ["DO NOT MODIFY STRUCTURE - SECURITY ENCRYPTED"],
        [],
        ["Date", "Title", "Category", "Method", "Type", "Amount", "Status", "Note"]
    ];

    data.forEach((e: any) => {
        worksheetData.push([
            new Date(e.date).toLocaleDateString('en-GB'),
            e.title.toUpperCase(),
            e.category.toUpperCase(),
            (e.paymentMethod || "CASH").toUpperCase(),
            e.type.toUpperCase(),
            e.amount,
            e.status.toUpperCase(),
            e.note || "-"
        ]);
    });

    const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);
    worksheet['!auth'] = "CBP-VAULT-V4"; // Hidden Signature
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Archive");
    XLSX.writeFile(workbook, `${bookName}_Archive.xlsx`);
};

// ২. পিডিএফ জেনারেশন ইঞ্জিন
export const generatePDFProtocol = (data: any[], bookName: string) => {
    const doc = new jsPDF();
    
    // হেডার ডিজাইন
    doc.setFontSize(22);
    doc.setTextColor(249, 115, 22);
    doc.setFont("helvetica", "bold");
    doc.text(BRANDING.name, 14, 20);
    
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.setFont("helvetica", "normal");
    doc.text(`SECURE LEDGER ARCHIVE | VAULT: ${bookName.toUpperCase()}`, 14, 28);
    doc.text(`GENERATED: ${new Date().toLocaleString()}`, 14, 33);

    const tableColumn = ["DATE", "TRANSACTION", "TAG", "METHOD", "TYPE", "AMOUNT", "STATUS"];
    const tableRows = data.map((e) => [
        new Date(e.date).toLocaleDateString('en-GB'),
        e.title.toUpperCase(),
        e.category.toUpperCase(),
        (e.paymentMethod || "CASH").toUpperCase(),
        e.type.toUpperCase(),
        e.amount.toLocaleString(),
        e.status.toUpperCase()
    ]);

    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 40,
        theme: 'grid',
        headStyles: { fillColor: [26, 26, 27], textColor: [255, 255, 255], fontSize: 8, fontStyle: 'bold' },
        styles: { fontSize: 8, cellPadding: 4 },
        didDrawPage: (dataArg) => {
            doc.setFontSize(7);
            doc.setTextColor(150);
            doc.text(`Generated by ${BRANDING.name} | ${BRANDING.credit}`, 14, doc.internal.pageSize.height - 10);
            doc.text(BRANDING.url, 160, doc.internal.pageSize.height - 10);
        }
    });

    doc.save(`${bookName}_Secure_Report.pdf`);
};