"use client";
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { X, Calendar, FileText, FileSpreadsheet, Download, Filter, Check, Loader2 } from 'lucide-react';
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import toast from 'react-hot-toast';

interface ExportModalProps {
    isOpen: boolean;
    onClose: () => void;
    entries: any[];
    bookName: string;
}

export const AdvancedExportModal = ({ isOpen, onClose, entries, bookName }: ExportModalProps) => {
    const [startDate, setStartDate] = useState('');
    const [endDate, setEndDate] = useState('');
    const [selectedCategory, setSelectedCategory] = useState('All');
    const [format, setFormat] = useState<'pdf' | 'excel'>('pdf');
    const [isExporting, setIsExporting] = useState(false);

    const categories = ['All', ...Array.from(new Set(entries.map((i: any) => i.category)))];

    const getFilteredData = () => {
        return entries.filter((item: any) => {
            const itemDate = new Date(item.date).getTime();
            const start = startDate ? new Date(startDate).getTime() : 0;
            const end = endDate ? new Date(endDate).getTime() : Infinity;
            return itemDate >= start && itemDate <= end && (selectedCategory === 'All' || item.category === selectedCategory);
        });
    };

    // AdvancedExportModal.tsx এর ভেতর handleExport ফাংশনটি এভাবে আপডেট করুন:

const handleExport = async () => {
    setIsExporting(true);
    const data = getFilteredData();

    if (data.length === 0) {
        toast.error("No data matches your filter");
        setIsExporting(false);
        return;
    }

    if (format === 'excel') {
        // ১. এক্সেল ব্র্যান্ডিং এবং সিগনেচার
        const worksheetData = [
            ["SOURCE: CASHBOOK PRO DIGITAL LEDGER"], // Row 1: Branding
            ["GENERATED ON: " + new Date().toLocaleString()], // Row 2: Metadata
            ["DO NOT MODIFY THE STRUCTURE OF THIS FILE FOR IMPORT"], // Row 3: Warning
            [], // Row 4: Empty
            ["Date", "Title", "Category", "Type", "Amount", "Status", "Note"] // Row 5: Headers
        ];

        data.forEach((e: any) => {
            worksheetData.push([
                new Date(e.date).toLocaleDateString(), e.title, e.category, e.type, e.amount, e.status, e.note || "-"
            ]);
        });

        const worksheet = XLSX.utils.aoa_to_sheet(worksheetData);
        
        // সিগনেচার ইনজেক্ট করা (এটি ইমপোর্টের সময় চেক করব)
        worksheet['!auth'] = "CBP-VAULT-VERIFIED-2026"; 
        
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, "Statement");
        XLSX.writeFile(workbook, `${bookName}_Report.xlsx`);
    } else {
        // ২. পিডিএফ ব্র্যান্ডিং
        const doc = new jsPDF();
        doc.setFontSize(20);
        doc.setTextColor(249, 115, 22); // Orange
        doc.text("CASHBOOK PRO", 14, 15);
        
        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text("SECURE DIGITAL LEDGER SYSTEM | DESIGNED BY RAHUL", 14, 22);

        autoTable(doc, {
            startY: 30,
            head: [["Date", "Title", "Category", "Type", "Amount", "Status"]],
            body: data.map((e: any) => [
                new Date(e.date).toLocaleDateString(), e.title, e.category, e.type, e.amount, e.status
            ]),
            didDrawPage: (dataArg) => {
                // ফুটারে ব্র্যান্ডিং (প্রতি পেজে থাকবে)
                doc.setFontSize(8);
                doc.setTextColor(150);
                doc.text("Generated by CashBook Pro - https://cash-book-pro.vercel.app/", 14, doc.internal.pageSize.height - 10);
            }
        });
        doc.save(`${bookName}_Report.pdf`);
    }

    toast.success("Exported with Branding");
    setIsExporting(false);
    onClose();
};

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
            <div onClick={onClose} className="absolute inset-0 bg-black/70 backdrop-blur-sm" />
            <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="bg-[var(--bg-card)] w-full max-w-md rounded-2xl shadow-2xl relative z-10 border border-[var(--border-color)] overflow-hidden">
                
                {/* Header */}
                <div className="p-6 border-b border-[var(--border-color)] flex justify-between items-center bg-[var(--bg-app)]">
                    <h2 className="text-sm font-black uppercase tracking-widest text-[var(--text-main)] flex items-center gap-2">
                        <Download size={16} className="text-orange-500"/> Export Data
                    </h2>
                    <button onClick={onClose} className="text-[var(--text-muted)] hover:text-red-500"><X size={18} /></button>
                </div>

                <div className="p-6 space-y-6">
                    {/* Date Range */}
                    <div className="space-y-2">
                        <label className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest flex gap-2"><Calendar size={12}/> Date Range</label>
                        <div className="flex gap-3">
                            <input type="date" className="app-input text-xs font-bold uppercase" value={startDate} onChange={e => setStartDate(e.target.value)} />
                            <input type="date" className="app-input text-xs font-bold uppercase" value={endDate} onChange={e => setEndDate(e.target.value)} />
                        </div>
                    </div>

                    {/* Categories */}
                    <div className="space-y-2">
                        <label className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest flex gap-2"><Filter size={12}/> Filter Category</label>
                        <div className="flex flex-wrap gap-2">
                            {categories.map((cat: any) => (
                                <button key={cat} onClick={() => setSelectedCategory(cat)} 
                                    className={`px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest border transition-all ${selectedCategory === cat ? 'bg-orange-500 text-white border-orange-500' : 'bg-[var(--bg-app)] text-[var(--text-muted)] border-[var(--border-color)]'}`}>
                                    {cat || 'All'}
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* Format */}
                    <div className="space-y-2">
                        <label className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest flex gap-2"><FileText size={12}/> Format</label>
                        <div className="grid grid-cols-2 gap-4">
                            <button onClick={() => setFormat('pdf')} className={`p-3 rounded-xl border flex flex-col items-center gap-1 transition-all ${format === 'pdf' ? 'border-red-500 bg-red-500/10 text-red-500' : 'border-[var(--border-color)] text-[var(--text-muted)]'}`}>
                                <FileText size={20} /> PDF
                            </button>
                            <button onClick={() => setFormat('excel')} className={`p-3 rounded-xl border flex flex-col items-center gap-1 transition-all ${format === 'excel' ? 'border-green-500 bg-green-500/10 text-green-500' : 'border-[var(--border-color)] text-[var(--text-muted)]'}`}>
                                <FileSpreadsheet size={20} /> Excel
                            </button>
                        </div>
                    </div>

                    <button onClick={handleExport} disabled={isExporting} className="app-btn-primary w-full py-3 text-xs tracking-widest shadow-xl flex items-center justify-center gap-2">
                        {isExporting ? <Loader2 className="animate-spin" size={14}/> : <Check size={14} />} Download Report
                    </button>
                </div>
            </motion.div>
        </div>
    );
};